a=int(input("enter first number "))
b=int(input("enter second number "))
s=(a+b)
c=(a-b)
d=(a/b)
e=(a*b)
f=(a%b)
print("SUM = ",s,end="\n")
print("A/B = ",c,end="\n")
print("Result = ",d,end="\n")
print("Product = ",e,end="\n")
print("Reminder = ",f,end="\n")

